name: Attach CN vs Worlds SeseiSei clips
on:
  push:
    paths:
      - '.github/workflows/attach-cnvsworlds-seseisei-clips.yml'
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add script tag
        run: ruby -pi -e 'sub(%r{</body>}, %q{<script src="./seseisei-clips.js?v=20260616"></script></body>}) unless $_.include?("seseisei-clips.js")' public/tournaments/cn-vs-worlds/index.html
      - name: Commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add public/tournaments/cn-vs-worlds/index.html
          git commit -m "Attach CN vs Worlds SeseiSei clips" || exit 0
          git push
